import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { InstallModule } from '../../types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

export default {
  order: 99,
  name: 'footer',
  category: 'common',
  generate: () => {
    const configPath = join(__dirname, '../../../generator.config.json');
    const pkgPath = join(__dirname, '../../../package.json');
    const config = JSON.parse(readFileSync(configPath, 'utf-8'));
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));

    return `---

**RSP Setup Copilot v${pkg.version}**

Repository: ${config.repoUrl}  
Documentation: ${config.webUrl}

_This file was automatically generated by [rsp-setup-copilot](${config.repoUrl})_`;
  }
} satisfies InstallModule;

